# Generated by Django 4.0.4 on 2022-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=250, verbose_name='phone')),
            ],
        ),
    ]
