# Generated by Django 4.0.4 on 2022-05-27 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='name',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='type',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='deptures',
            field=models.DateTimeField(auto_now_add=True, verbose_name='depture'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_from',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_to',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is active'),
        ),
        migrations.DeleteModel(
            name='AirplaneType',
        ),
    ]
